title: The Book Keeper's Archive
description: >-
  Logs and dossiers of all known teams, including restricted and inactive groups.
theme: minima
minima:
  navigation_links:
    - title: "Home"
      url: "/"
    - title: "Team 14"
      url: "/team_14/team_14.html"

# Optional settings for minima theme
author: The Book Keeper

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty
future: true
highlighter: rouge
markdown: kramdown
plugins: ['jekyll-paginate']

# Jekyll collections
# Documentation - https://jekyllrb.com/docs/collections/
collections_dir: collections
collections:
  logs:
    output: true
    permalink: /:collection/:title
