title: The Book Keeper's Archive
description: >-
  Logs and dossiers of all known teams, including restricted and inactive groups.
remote_theme: "minima"

excerpt_separator: "<!--more-->"

# Optional settings for minima theme
author: The Book Keeper

# Build settings
markdown: kramdown

# Permalinks
permalink: pretty
future: true
highlighter: rouge

plugins: ['jekyll-paginate']

# # Jekyll collections
# # Documentation - https://jekyllrb.com/docs/collections/
# collections:
#   collections_dir: logs
#   team14:
#     output: true
#     slug: /team14_logs/:name
